### ISSUE TITLE
merger should delete old files upon detection

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/firehose-ethereum#11]
Merger keeps finding new files that are old, but it doesn't delete them for some reason.

Re: https://github.com/streamingfast/sf-ethereum/issues/10

It seems to wait until it can merge a block, then delete the old files.  But it might never merge a block because there are too many old files.

**Comment by maoueh** [comment]
@billettc @froch More work for you guys?

**Comment by matthewdarwin** [comment]
The test case is here is to have an mindreader running generating old one-block files while other mindreaders are generating latest one-block files.

**Comment by matthewdarwin** [comment]
![image](https://user-images.githubusercontent.com/26171839/148859081-b395f05f-c86f-4d81-8eae-cc12f2893609.png)

Latest merger is **really bad** compared to the old merger.  I've now stopped generating old blocks to make it stable.  Let's see how it is over the next little bit.

**Comment by matthewdarwin** [comment]
BTW, count of one-block files went down because I have been manually removing them.

**Comment by maoueh** [comment]
I think it's fixed now.
