### ISSUE TITLE
merger used to count how many one block files were available

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/firehose-ethereum#13]
merger used to count how many one block files were available.  Now get messages like:

```bundle not completed after retrieving one block file (merger/merger.go:112){"bundle": "bundle_size: 100, last_merge_block_num: 0, inclusive_lower_block_num: 14257400, exclusive_highest_block_limit: 14257500"}```

Please put back the old behaviour where it showed how many one-block files have been received for the 100-block bundle.

**Comment by matthewdarwin** [comment]
Also `too_old_files_count` seems always to be 0 now.

**Comment by maoueh** [comment]
With all the changes that went in the merger, I think we can close this.
