### ISSUE TITLE
How to consume the firehose block stream?

### ISSUE THREAD

**Issue by paymog** [streamingfast/firehose-ethereum#36]
I've read through the [firehose docs](https://firehose.streamingfast.io/introduction/firehose-overview) and it's not clear how the block stream produced by firehouse should be consumed. Does the gRPC server provide an interface that is compatible with the eth JSON-RPC interface? Does Firehose integrate tightly with graph node (considering it's mentioned in the [graph node docs](https://docs.thegraph.academy/the-graph-ecosystem/infrastructure/firehose))? How should the grpc server be started, in the [startup YAML](https://firehose.streamingfast.io/firehose-setup/ethereum/installation-1#config-file-in-detail) or [as a subcommand](https://firehose.streamingfast.io/firehose-setup/ethereum/synchronization#data-analyzation-and-streaming)?

**Comment by matthewdarwin** [comment]
Probably easier to discuss in the discord.  See the link on the home page. https://www.streamingfast.io/

**Comment by maoueh** [comment]
Closing as this discussion is indeed better for Discord, feel free to add issue on https://github.com/streamingfast/firehose-docs afterwards if required.
