### ISSUE TITLE
Merger stuck at block 31000

### ISSUE THREAD

**Issue by paymog** [streamingfast/firehose-ethereum#38]
It seems that my merger is now stuck at block 31000. I see the following log line emitted over and over

```
firehose-mainnet-6f8bbfbd75-gcwpc firehose {"severity":"WARNING","timestamp":"2022-10-21T15:44:42.420585258-04:00","logger":"bstream","message":"too many consecutive unlinkable blocks","block":"#109903 (b4a118481e568b1c)","consecutive_unlinkable_blocks":77100,"last_block_sent":"#31272 (00689cb504900f40)","logging.googleapis.com/labels":{}}
```

and here's a more complete sample of log lines:

```
firehose-mainnet-6f8bbfbd75-gcwpc firehose {"severity":"INFO","timestamp":"2022-10-21T15:44:36.322716469-04:00","logger":"index-builder","message":"reading from blocks store: file does not (yet?) exist, retrying in","filename":"/data/firehose/storage/merged-blocks/0000031000.dbin.zst","base_filename":"0000031000","retry_delay":4,"logging.googleapis.com/labels":{}}
firehose-mainnet-6f8bbfbd75-gcwpc firehose {"severity":"INFO","timestamp":"2022-10-21T15:44:37.068411556-04:00","logger":"reader.geth","message":"forkchoice requested sync to new head    number=15,798,650 hash=d179b5..c50f7d","logging.googleapis.com/labels":{}}
firehose-mainnet-6f8bbfbd75-gcwpc firehose {"severity":"INFO","timestamp":"2022-10-21T15:44:40.322901399-04:00","logger":"index-builder","message":"reading from blocks store: file does not (yet?) exist, retrying in","filename":"/data/firehose/storage/merged-blocks/0000031000.dbin.zst","base_filename":"0000031000","retry_delay":4,"logging.googleapis.com/labels":{}}
firehose-mainnet-6f8bbfbd75-gcwpc firehose {"severity":"INFO","timestamp":"2022-10-21T15:44:40.834577546-04:00","logger":"reader.geth","message":"imported new chain segment               blocks=71   txs=389  mgas=8.229  elapsed=8.235s    mgasps=0.999  number=369,258    hash=f8be77..e6c618 age=7y1mo2w  dirty=5.43MiB","logging.googleapis.com/labels":{}}
firehose-mainnet-6f8bbfbd75-gcwpc firehose {"severity":"WARNING","timestamp":"2022-10-21T15:44:42.420585258-04:00","logger":"bstream","message":"too many consecutive unlinkable blocks","block":"#109903 (b4a118481e568b1c)","consecutive_unlinkable_blocks":77100,"last_block_sent":"#31272 (00689cb504900f40)","logging.googleapis.com/labels":{}}
firehose-mainnet-6f8bbfbd75-gcwpc firehose {"severity":"INFO","timestamp":"2022-10-21T15:44:44.323103322-04:00","logger":"index-builder","message":"reading from blocks store: file does not (yet?) exist, retrying in","filename":"/data/firehose/storage/merged-blocks/0000031000.dbin.zst","base_filename":"0000031000","retry_delay":4,"logging.googleapis.com/labels":{}}
firehose-mainnet-6f8bbfbd75-gcwpc firehose {"severity":"INFO","timestamp":"2022-10-21T15:44:48.323232598-04:00","logger":"index-builder","message":"reading from blocks store: file does not (yet?) exist, retrying in","filename":"/data/firehose/storage/merged-blocks/0000031000.dbin.zst","base_filename":"0000031000","retry_delay":4,"logging.googleapis.com/labels":{}}
firehose-mainnet-6f8bbfbd75-gcwpc firehose {"severity":"INFO","timestamp":"2022-10-21T15:44:48.996961958-04:00","logger":"reader.geth","message":"imported new chain segment               blocks=804  txs=708  mgas=15.726 elapsed=8.115s    mgasps=1.938  number=370,062    hash=266bdd..3b7689 age=7y1mo2w  dirty=4.67MiB","logging.googleapis.com/labels":{}}
firehose-mainnet-6f8bbfbd75-gcwpc firehose {"severity":"INFO","timestamp":"2022-10-21T15:44:49.077330751-04:00","logger":"reader.geth","message":"forkchoice requested sync to new head    number=15,798,651 hash=31b649..2c1d7c","logging.googleapis.com/labels":{}}
firehose-mainnet-6f8bbfbd75-gcwpc firehose {"severity":"WARNING","timestamp":"2022-10-21T15:44:50.162217455-04:00","logger":"bstream","message":"too many consecutive unlinkable blocks","block":"#110003 (7b770ad57aa913a8)","consecutive_unlinkable_blocks":77200,"last_block_sent":"#31272 (00689cb504900f40)","logging.googleapis.com/labels":{}}
```

Are the unlinkable blocks an issue? If so, how can I resolve them?

**Comment by paymog** [comment]
ah got it! I ended up wiping the data directory and starting from scratch which seemed to fix it. Good to know there's a way to resolve this with geth. I guess in this specific case, I should use a block prior to 31000 when doing the rewind. Is that correct? Is it better to go back further in time? 

If I have two reader nodes sharing the same one-block store, should I make sure they don't share the same data-dir? eg: have two reader node pods (in k8s) with independent volumes for the datadir but use the same s3 bucket for the one-block, merged, forked and index dirs?

**Comment by maoueh** [comment]
>  Is that correct? Is it better to go back further in time?

Yeah you are correct, should probably use like `hole - 500` as the input, it's safe to go back a bit in time. So early in the chain however, `setHead` actually start back from genesis anyway, so it's easier to simply restart.

> If I have two reader nodes sharing the same one-block store, should I make sure they don't share the same data-dir?

Exact, they have they own data dir so they both sync with the chain, but as you said, they both write to the same one block store, the `merger` is intelligent and will delete older files that are not required.

When using this setup, you can configure the flag `reader-node-oneblock-suffix` differently for both `reader-node`, this one some storage engine. Setting the flag make reader-node write independent files representing the same block, it helps deals with problem of read/write consistency on the same filename we've seen in the past on some storage solution, like Ceph. The `merger` is handles those correctly.

**Comment by paymog** [comment]
Awesome, thank you for all the help. I'll try to make a PR in the next couple days to document all my learnings so other devs have an easier time getting things up and running.

**Comment by maoueh** [comment]
@seanmooretechwriter Is our technical writer, pretty sure he could also make a few adjustments by looking at all the conversation we had over the past weeks :)

**Comment by paymog** [comment]
Oh right! @seanmooretechwriter I'd be happy to chat (over text/audio/video) if you'd like to get an overview of what I've learned - hopefully that will make writing docs a bit easier 🙂

**Comment by seanmooretechwriter** [comment]
Hi @paymog 

Good to hear from you!

Ok, this sounds like a great idea. Please let me know what your availability looks like and we can set up a time and day to chat and go over all of this. I'll read through more of this Git issue prior to our chat.

Thank you a ton for your time and the awesome and valuable feedback! :)

**Comment by seanmooretechwriter** [comment]
Summary of our call with Goldsky’s paymahn (whom are in discussion with the Foundation, they’re serving private subgraphs, etc..)

> We pay a lot for RPC providers
> They aren’t very performant
> Adding our own caching layers
> Stumbled upon Firehose, which seems to do everything for us.
Goals:
* Interested in a 3x speed increase just for subgraphs.
* They started rolling out, and they saw more like a 7x or 8x in speed.
* Also interested in reliability increase, by Firehose’s simpler design (data push), and avoiding all those crappy RPC nodes, always out of sync, with bugs and issues.
* Very interested in the archive product (EVM Executor)
Experience report:
  * Wasn’t clear how to run Firehose.
  * Docs seemed a bit out of date.
  * I needed to run a consensus client, wasn’t in the docs.
    * (this is Ethereum specific, we don’t have chain-specific docs sections yet)
  * Bash scripts from Matt were really really useful.
  * Got it running in Docker well too.
  * Would be a huge time saver to find LINKS to prebuilt docker images. Had to search for them.
    TODO: decide if we want to support such images, and if we’re comfortable making it easy. There’s a bit of a commitment there.
	  But in any case, they,re using them.. so might as well document it an ease their path.
  * Would be amazing to have ARM and X86 builds, for Firehose.
  * Would be amazing: a docker-compose setup (don’t we have that already? k8s deployments? bash is good, but could have been faster still)
  * Interested in understanding what Highly Available setups look like.
    * TODO: rework the Components page, and perhaps have a “High Availability” page, where the “High Availability” considerations of each components converge.
	  * TODO: Sean: perhaps bump up the heading levels so the side menu shows more of the content of the page.. Right now, only the component is listed in there.
  * Related to configs that Matt made for the Goerli mainnet:
    https://github.com/streamingfast/firehose-ethereum/blob/42997ba73fb819719c6fab0d513c855276eea820/devel/sync-mainnet/sync-mainnet.yaml#L11
    * --common-live-blocks-addr makes it WAIT
      Would be awesome if it wouldn’t WAIT, and just poll the relayer, and not block.
 	  Would be awesome if it started even if we’re still sync’ing, even if live blocks aren’t ready.
    * TODO: stepd: document what the combined-index-builder does.. what’s the HA setup there. How does it relate to other components?
	  * Perhaps in an Ethereum-specific doc? How to lay that out?
I explained Total Ordering, (especially the relation between call handlers and logs), he seemed really happy. Would love to have hit that in the docs.
TODO: Document total ordering.
`graph-node` issues, asked to forward to The Graph Discord.
