### ISSUE TITLE
Devel sync-mainnet stuck on startup (can't find peers)

### ISSUE THREAD

**Issue by uberspot** [streamingfast/firehose-ethereum#46]
Hi,

i'm having an issue with running the example from the devel/sync-mainnet/ folder and all links to your discord seem to be expired in docs so I can't find/join it. 

Lighthouse release used: https://github.com/sigp/lighthouse/releases/tag/v3.3.0 
Config used(no changes, just for testing): https://github.com/streamingfast/firehose-ethereum/tree/develop/devel/sync-mainnet 

streamingfast/go-ethereum release used: `release/geth-v1.10.26-fh2.1`

```
fireeth --version
fireeth version dev
```

Issue: Basically the geth node can't find peers. It gets stuck in this state for >30minutes and then I terminate it. I checked the security groups in AWS and they all seem reasonably open for the ports it needs. I tried opening the ports completely too to 0.0.0.0/0. Other aws compute with rocketpool and erigon nodes running in the same security group work fine so I don't think it's the network. 

For testing: 

`export CHECKPOINT_SYNC_URL=https://sync.invis.tools`

Consensys output: https://pastecode.io/s/djzjdw8i 

Firehose output:  https://pastecode.io/s/ym9pfdkk

**Comment by maoueh** [comment]
From the consensus output, it seems that it was never able to contact the execution client (`geth` here managed by `firehose`).

All I see there is `Connection refused` errors. Are you able locally from the machine that is running `lighthouse` to contact the execution endpoint? Maybe they are running on two different machine and hence, you would need to update `http://localhost:9551` in the `lighthouse` config?

**Comment by maoueh** [comment]
Nothing we can do, peering issue is something outside the scope we can deal within Firehose. https://geth.ethereum.org/docs/fundamentals/peer-to-peer might help, I've added that to the doc.
