### ISSUE TITLE
When substream client restart, firehose doesn't return block from the cursor, it returns older block

### ISSUE THREAD

**Issue by 0xsarvesh** [streamingfast/firehose-ethereum#47]
If there is restart from consumer, firehose server always return blocks from nearest block in multiple of batch size. 

Sink code also throws error 
```
block continuity on first block after restarting from cursor does not follow
```
https://github.com/streamingfast/substreams-consumer/blob/develop/main.go#L290

For example If batch size of 1000,  if client restarts & cursor is at 10543445.  Firehose will start sending block from 10543000.

```
    substreams-sub-request-block-range-size: 1000
```

Here is conversation in discord for more details: 
https://discord.com/channels/666749063386890256/1041633976034533406/1060884898560364555

**Comment by sduchesneau** [comment]
@0xsarvesh 

hi, I can't reproduce on the currently deployed code on our *unstable* endpoint: 
* firehose-ethereum `0bbe0a0` (contains substreams `ba8931193914`)


```cursor: 9Xk3JwQKtPlOE6FpkVRuOKWwLpc_DFhnXA3gIBRI09n38XTDjM-hUmkgPhjUkav23xTqSAj92N7PQC1zocUF6ITtxro1vnA5QS0kkI7s-LG8eaH1ag0eJ7ljVuiEYNDSXTndZwOtKLAB5tO2aPSLbxdkZ8MnLmCxjj5T8NRScaFF6ntmxmmpJsjX0qrFoINGqeomQ-aikHiiVTIuK0oMP82LZQ==
block:
    id: 59fb1166ab7b8ef541262113ba612dc8c5ede752aca17f837235c1b7c75f2192
    number: 28965```
    
`go run . api-unstable.streamingfast.io:443 https://github.com/streamingfast/substreams-eth-block-meta/releases/download/v0.3.1/substreams-eth-block-meta-v0.3.1.spkg kv_out --production-mode`

gives me the following: 
```
...
2023-01-11T09:52:32.542-0500 INFO (consumer) checking first received block {"block_at_cursor": "#28965 (59fb1166ab7b8ef541262113ba612dc8c5ede752aca17f837235c1b7c75f2192)", "first_block": "#28966 (219b60b6a20d6f8e37d812f2bff710f5e568e94cae9c537d8a69e4f73fec825f)"}
```

Can you build from 0bbe0a0 and see if you still experience the issue ?
If you do, please give me a copy of your 'state.yaml' file as well as the command that you are running.
I may also need the 'spkg'  file if I still can't reproduce.

Thank you!

**Comment by sduchesneau** [comment]
Note that the 'unstable' endpoint is not something that you will want to use regularly, but you can try it for the purpose of debugging this ^^

**Comment by maoueh** [comment]
`mainnet.eth.streamingfast.io:443` can be used now, latest version deployed there.

**Comment by 0xsarvesh** [comment]
Thanks you @sduchesneau  @maoueh  I will check on this & revert back.

**Comment by 0xsarvesh** [comment]
I checked with the latest build of fireeth, it's not re-produceable. Thank you
