### ISSUE TITLE
Chache glitch and log spam

### ISSUE THREAD

**Issue by matsuro-hadouken** [streamingfast/firehose-ethereum#62]
After upgrade to v1.4.1 storm of `calling updateCache` can be observed from unknown source.

![image](https://github.com/streamingfast/firehose-ethereum/assets/50751381/822bc357-e28d-4047-ac12-e3a93fb10957)

There is additional repetative messages:
```
INFO (rpc-cache) rpc cache not found {"filename": "cache-0013142000-0013143000.cache", "read_store_url": "file:///firehose/sf-data/rpc-cache", "error": "not found"}
INFO (firehose.tier2) not saving cache, because empty {"parent_trace_id": "ce1298b5ee1e9df69170ea2201d7fc79", "trace_id": "f7a89284e5c91d73982d4caa0dc4d4b2", "module": "store_supply", "block_range": "[13141000, 13142000)"} 
```

**Comment by sduchesneau** [comment]
this comes from a build problem, these debug lines are not committed. I will produce another build with clean state.

**Comment by sduchesneau** [comment]
Please try with the "rebuilt" binaries for v1.4.1.
Same commit hash, just a new binary.

Thanks

**Comment by matsuro-hadouken** [comment]
This fixed the issue. Now everything works as expected. Can be closed. Thank you !
