### ISSUE TITLE
/healthz returns "is_ready: true" when shutting down

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/firehose-ethereum#66]
When using `common-system-shutdown-signal-delay: 30s` this gives time for the load-balancer to stop sending traffic to the endpoint before it shuts down.  However /healthz URL returns `is_ready: true` during this time, so there is no way for the load balancer to understand it is in shutdown state, making the flag "useless".

**Comment by maoueh** [comment]
This seems to be a bug, which app is this?

**Comment by matthewdarwin** [comment]
substreams tier1.  Might apply to firehose or substreams tier2 as well. I didn't check those.

**Comment by maoueh** [comment]
Definitely a bug, the `firehose` app has a check to check is shutdown is pending: https://github.com/streamingfast/firehose/blob/develop/app/firehose/app.go#L202-L214

What version/commit are you using exactly, could be a recent regression..

**Comment by matthewdarwin** [comment]
I'm testing 1.4.7 before we roll it out.

**Comment by matthewdarwin** [comment]
Closing in favour of: https://github.com/streamingfast/firehose-core/issues/9
