### ISSUE TITLE
Polygon Deposit Transactions are not part of block

### ISSUE THREAD

**Issue by 0xsarvesh** [streamingfast/firehose-ethereum#72]
Polygon has special transaction that Deposit assets from mainnet to polygon chain. 
These transactions are not part of Firehose blocks. 

Example Transaction: https://polygonscan.com/tx/0x8f3e05c5af7d601a6015c4fdbb68a04cbf0305fe2740920ce70f81ed1943a194

As per the release notes V1.3.6. State sync transactions should be tracked. But firehose node is not tracking it. 
https://github.com/streamingfast/firehose-ethereum/releases/tag/v1.3.6

>  This release fixes polygon "StateSync" transactions by grouping the calls inside an artificial transaction.

Discord Thread: https://discord.com/channels/666749063386890256/982135810742697984/1142136382853234719

**Comment by sduchesneau** [comment]
probably the same as this: https://github.com/streamingfast/firehose/issues/25

**Comment by sduchesneau** [comment]
Fixed here: https://github.com/streamingfast/firehose-ethereum/pull/74

This will require reprocessing the blocks from genesis.

**Comment by 0xsarvesh** [comment]
Thanks @sduchesneau  
When this will be officially released ?

**Comment by sduchesneau** [comment]
@0xsarvesh just wanted to let you know that we've now switched to serving the fixed blocks on our https://polygon.streamingfast.io firehose endpoint.
