### ISSUE TITLE
Reprocess Polygon Mainnet

### ISSUE THREAD

**Issue by jubeless** [streamingfast/firehose-ethereum#75]
**OKR: Build a raving community of developers around Substreams / Publish 40 pieces of contents on Medium or YouTube**

**Goal: Enable rewards for `polygon` for SbS on the network**
Airstack needs it?

Need to reprocess due to fixes here: https://github.com/streamingfast/firehose/issues/25

**Comment by sduchesneau** [comment]
running this, taking the time to compare some ranges with the parallel-transaction option

**Comment by sduchesneau** [comment]
done
